FROM maven:3.8-openjdk-8 AS build
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src src

RUN mvn clean package  -Dskiptests

FROM openjdk:8-jre-slim-stretch

RUN mkdir /uploads

COPY --from=build /target/Job-Board-Platform-for-connecting-JobSeekers-with-employers-0.0.1-SNAPSHOT.jar Job-Board-Platform-for-connecting-JobSeekers-with-employers.jar

EXPOSE 9095

ENTRYPOINT [ "java","-jar","Job-Board-Platform-for-connecting-JobSeekers-with-employers.jar"]